server:
  port: 8000
  address: 192.168.47.1



# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bysz?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&charset=utf8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:com/yuanhuafeng/employment/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.yuanhuafeng.employment


logging:
  level:
    com:
      example:
        mapper:
          debug

